version = 1

[[annotations]]
path = [
  ".codespellignore",
  ".gitattributes",
  ".pre-commit-config.yaml",
  ".readthedocs.yml",
  "**/.gitignore",
  "pyproject.toml",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["docs/**"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["src/**/generated/**"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "LGPL-3.0-or-later"
